apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DEEPSEEK_API_KEY: c2stNWVmMTNjNmVlNTRiNGQ5NDg1NWM0MjFkMDg3OWExZTA=
  FOOTBALL_API_KEY: N2QyMmZkNTc4Njg3MTY1NGUxNjI4M2I4MDc2MGRhOTU=